# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('slug', models.SlugField()),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=512)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
                ('priority', models.IntegerField()),
                ('alt', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('slug', models.SlugField()),
                ('description', models.CharField(max_length=1024)),
                ('sales', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('meat', models.BooleanField(default=False)),
                ('meat_type', models.CharField(choices=[('PO', 'Pork'), ('BF', 'Beef'), ('CH', 'Chicken'), ('OT', 'Other'), ('NA', 'Not Meat')], default='PO', max_length=2)),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegetable_heavy', models.BooleanField(default=False)),
                ('low_sugar', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('lasts_a_week', models.BooleanField(default=False)),
                ('lasts_a_month', models.BooleanField(default=False)),
                ('low_preparation', models.BooleanField(default=False)),
                ('pairings', models.ManyToManyField(blank=True, null=True, related_name='_product_pairings_+', to='products.Product')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Producer')),
                ('same_producer', models.ManyToManyField(blank=True, null=True, related_name='_product_same_producer_+', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Article')),
                ('heritage', models.BooleanField(default=False)),
            ],
            bases=('products.article',),
        ),
        migrations.CreateModel(
            name='HistoryHeader',
            fields=[
                ('header_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Header')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.History')),
            ],
            bases=('products.header',),
        ),
        migrations.CreateModel(
            name='HistoryPhoto',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Photo')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.History')),
            ],
            bases=('products.photo',),
        ),
        migrations.CreateModel(
            name='HistoryText',
            fields=[
                ('text_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Text')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.History')),
            ],
            bases=('products.text',),
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Article')),
                ('rating', models.SmallIntegerField()),
            ],
            bases=('products.article',),
        ),
        migrations.CreateModel(
            name='ImpactHeader',
            fields=[
                ('header_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Header')),
                ('impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Impact')),
            ],
            bases=('products.header',),
        ),
        migrations.CreateModel(
            name='ImpactPhoto',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Photo')),
                ('impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Impact')),
            ],
            bases=('products.photo',),
        ),
        migrations.CreateModel(
            name='ImpactText',
            fields=[
                ('text_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Text')),
                ('impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Impact')),
            ],
            bases=('products.text',),
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Article')),
                ('prep_time', models.IntegerField()),
                ('difficulty', models.SmallIntegerField()),
            ],
            bases=('products.article',),
        ),
        migrations.CreateModel(
            name='PreparationHeader',
            fields=[
                ('header_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Header')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Preparation')),
            ],
            bases=('products.header',),
        ),
        migrations.CreateModel(
            name='PreparationPhoto',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Photo')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Preparation')),
            ],
            bases=('products.photo',),
        ),
        migrations.CreateModel(
            name='PreparationText',
            fields=[
                ('text_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Text')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Preparation')),
            ],
            bases=('products.text',),
        ),
        migrations.CreateModel(
            name='ProductHeader',
            fields=[
                ('header_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Header')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            bases=('products.header',),
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Photo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            bases=('products.photo',),
        ),
        migrations.CreateModel(
            name='ProductText',
            fields=[
                ('text_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Text')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            bases=('products.text',),
        ),
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Article')),
                ('people_supported', models.SmallIntegerField()),
            ],
            bases=('products.article',),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Article')),
                ('prep_time', models.IntegerField()),
                ('dificulty', models.SmallIntegerField()),
            ],
            bases=('products.article',),
        ),
        migrations.CreateModel(
            name='RecipeHeader',
            fields=[
                ('header_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Header')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Recipe')),
            ],
            bases=('products.header',),
        ),
        migrations.CreateModel(
            name='RecipePhoto',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Photo')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Recipe')),
            ],
            bases=('products.photo',),
        ),
        migrations.CreateModel(
            name='RecipeText',
            fields=[
                ('text_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Text')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Recipe')),
            ],
            bases=('products.text',),
        ),
        migrations.AddField(
            model_name='product',
            name='environmental_impact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Impact'),
        ),
        migrations.AddField(
            model_name='product',
            name='history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.History'),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Preparation'),
        ),
        migrations.AddField(
            model_name='product',
            name='provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Provenance'),
        ),
        migrations.AddField(
            model_name='product',
            name='recipes',
            field=models.ManyToManyField(blank=True, null=True, to='products.Recipe'),
        ),
    ]
