# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170111_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='path',
            new_name='image',
        ),
    ]
