# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 21:30
from __future__ import unicode_literals

from django.db import migrations

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170115_2022'),
    ]

    operations = [
	migrations.CreateModel('Photo', fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField()),
                ('priority', models.IntegerField()),
                ('alt', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512))]),
	migrations.CreateModel('ProductPhoto', fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Photo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            bases=('products.photo',),
        ),
    ]
